INSERT INTO categories (name, slug, description, seo_title, seo_description, sort_order, is_active) VALUES
('Home & Kitchen', 'home-kitchen',
 'Practical home and kitchen picks that make everyday cooking and cleaning easier.',
 'Best Home & Kitchen Products (2026) | DealStoker',
 'Curated home and kitchen deals on Amazon.com — cookware, storage, and everyday essentials.',
 10, TRUE),
('Electronics', 'electronics',
 'Popular consumer electronics with strong ratings and reliable everyday value.',
 'Best Electronics Deals | DealStoker',
 'Shop curated electronics picks on Amazon.com — headphones, chargers, and smart gadgets.',
 20, TRUE),
('Outdoor & Sports', 'outdoor-sports',
 'Gear for workouts, camping, and weekend adventures without overpaying.',
 'Best Outdoor & Sports Gear | DealStoker',
 'Discover outdoor and sports essentials curated for Amazon.com shoppers.',
 30, TRUE);

INSERT INTO products (
    source, external_id, marketplace, title, slug, description, image_url,
    price_amount, currency, availability, rating, review_count, detail_page_url, brand,
    features_json, status, seo_title, seo_description, primary_category_id, published_at, last_synced_at
) VALUES
('AMAZON', 'B0D1XD1ZV3', 'www.amazon.com',
 'Ninja Crispi 4-in-1 Portable Glass Air Fryer Cooking System',
 'ninja-crispi-portable-air-fryer',
 'A compact air fryer system built for quick weeknight meals with less oil and easy cleanup.',
 'https://m.media-amazon.com/images/I/71QwQhF+QhL._AC_SL1500_.jpg',
 149.99, 'USD', 'InStock', 4.6, 8200,
 'https://www.amazon.com/dp/B0D1XD1ZV3', 'Ninja',
 '["Portable glass containers","Air fry, crisp, bake, and dehydrate","Easy cleanup"]',
 'PUBLISHED', 'Ninja Crispi Portable Air Fryer Review & Deal | DealStoker',
 'See pricing, key features, and where to buy the Ninja Crispi portable air fryer on Amazon.',
 (SELECT id FROM categories WHERE slug = 'home-kitchen'), NOW(), NOW()),

('AMAZON', 'B09B8R86BS', 'www.amazon.com',
 'Amazon Basics Digital Kitchen Scale with LCD Display',
 'amazon-basics-digital-kitchen-scale',
 'A simple, accurate kitchen scale for baking and meal prep with a clear LCD readout.',
 'https://m.media-amazon.com/images/I/61vZ4dQK8dL._AC_SL1500_.jpg',
 12.99, 'USD', 'InStock', 4.7, 95000,
 'https://www.amazon.com/dp/B09B8R86BS', 'Amazon Basics',
 '["Precise gram/ounce modes","Tare function","Compact footprint"]',
 'PUBLISHED', 'Amazon Basics Digital Kitchen Scale | DealStoker',
 'Affordable digital kitchen scale for baking accuracy — check current Amazon price.',
 (SELECT id FROM categories WHERE slug = 'home-kitchen'), NOW(), NOW()),

('AMAZON', 'B08G9PRQ92', 'www.amazon.com',
 'Rubbermaid Brilliance Food Storage Container Set',
 'rubbermaid-brilliance-food-storage-set',
 'Leak-resistant clear containers that stack neatly and keep leftovers fresh.',
 'https://m.media-amazon.com/images/I/81Z5p7bG5cL._AC_SL1500_.jpg',
 34.99, 'USD', 'InStock', 4.8, 120000,
 'https://www.amazon.com/dp/B08G9PRQ92', 'Rubbermaid',
 '["Leak-resistant lids","Clear visibility","Microwave and dishwasher safe"]',
 'PUBLISHED', 'Rubbermaid Brilliance Storage Set Deal | DealStoker',
 'Curated pick for meal prep and leftovers — Rubbermaid Brilliance on Amazon.com.',
 (SELECT id FROM categories WHERE slug = 'home-kitchen'), NOW(), NOW()),

('AMAZON', 'B0BSHF7WHW', 'www.amazon.com',
 'COSORI 12-in-1 Air Fryer Oven Combo',
 'cosori-12-in-1-air-fryer-oven',
 'A versatile countertop oven that air fries, bakes, and roasts for family-sized portions.',
 'https://m.media-amazon.com/images/I/71Q5oZ8bQGL._AC_SL1500_.jpg',
 119.99, 'USD', 'InStock', 4.6, 21000,
 'https://www.amazon.com/dp/B0BSHF7WHW', 'COSORI',
 '["12 cooking functions","Large capacity","Preheat and keep warm"]',
 'PUBLISHED', 'COSORI 12-in-1 Air Fryer Oven | DealStoker',
 'Compare features and current pricing for the COSORI air fryer oven combo.',
 (SELECT id FROM categories WHERE slug = 'home-kitchen'), NOW(), NOW()),

('AMAZON', 'B09JQL3NWT', 'www.amazon.com',
 'Soundcore Anker Life Q30 Hybrid Active Noise Cancelling Headphones',
 'soundcore-life-q30-anc-headphones',
 'Comfortable over-ear headphones with hybrid ANC and long battery life for travel and work.',
 'https://m.media-amazon.com/images/I/61kI0Xy4vFL._AC_SL1500_.jpg',
 59.99, 'USD', 'InStock', 4.5, 90000,
 'https://www.amazon.com/dp/B09JQL3NWT', 'Soundcore',
 '["Hybrid active noise cancelling","Up to 40 hours playtime","Hi-Res audio mode"]',
 'PUBLISHED', 'Soundcore Life Q30 Headphones Deal | DealStoker',
 'Popular ANC headphones with strong battery life — see Amazon pricing on DealStoker.',
 (SELECT id FROM categories WHERE slug = 'electronics'), NOW(), NOW()),

('AMAZON', 'B0B1N7X6R4', 'www.amazon.com',
 'Anker 737 Power Bank (PowerCore 24K)',
 'anker-737-power-bank-24k',
 'High-capacity portable charger with fast USB-C output for phones and laptops on the go.',
 'https://m.media-amazon.com/images/I/61xYkXwQ0gL._AC_SL1500_.jpg',
 99.99, 'USD', 'InStock', 4.7, 18000,
 'https://www.amazon.com/dp/B0B1N7X6R4', 'Anker',
 '["24,000mAh capacity","140W max output","Smart digital display"]',
 'PUBLISHED', 'Anker 737 Power Bank Review & Price | DealStoker',
 'A travel-ready power bank for phones and laptops — check the latest Amazon deal.',
 (SELECT id FROM categories WHERE slug = 'electronics'), NOW(), NOW()),

('AMAZON', 'B09JZM6Y6C', 'www.amazon.com',
 'Apple AirTag 4 Pack',
 'apple-airtag-4-pack',
 'Bluetooth trackers that help you find keys, bags, and other everyday items via Find My.',
 'https://m.media-amazon.com/images/I/71gY9E+1QhL._AC_SL1500_.jpg',
 79.99, 'USD', 'InStock', 4.7, 70000,
 'https://www.amazon.com/dp/B09JZM6Y6C', 'Apple',
 '["Precision Finding with U1","Privacy-first design","Replaceable battery"]',
 'PUBLISHED', 'Apple AirTag 4 Pack Deal | DealStoker',
 'Track what matters with Apple AirTag — current Amazon.com pricing and overview.',
 (SELECT id FROM categories WHERE slug = 'electronics'), NOW(), NOW()),

('AMAZON', 'B0BDHB9Y8H', 'www.amazon.com',
 'Belkin BoostCharge Pro 2-in-1 Wireless Charging Stand',
 'belkin-boostcharge-pro-wireless-stand',
 'A MagSafe-compatible stand that charges iPhone and Apple Watch together on your desk.',
 'https://m.media-amazon.com/images/I/61QbqF6G0gL._AC_SL1500_.jpg',
 69.99, 'USD', 'InStock', 4.5, 9000,
 'https://www.amazon.com/dp/B0BDHB9Y8H', 'Belkin',
 '["MagSafe fast wireless charging","Apple Watch charger included","Desk-friendly design"]',
 'PUBLISHED', 'Belkin BoostCharge Pro Wireless Stand | DealStoker',
 'Desk charging made simple — Belkin BoostCharge Pro details and Amazon link.',
 (SELECT id FROM categories WHERE slug = 'electronics'), NOW(), NOW()),

('AMAZON', 'B07QJWZK6H', 'www.amazon.com',
 'Hydro Flask Standard Mouth Water Bottle with Flex Cap',
 'hydro-flask-standard-mouth-bottle',
 'Insulated stainless bottle that keeps drinks cold for hours on hikes, gym days, and travel.',
 'https://m.media-amazon.com/images/I/61o6W4fF8HL._AC_SL1500_.jpg',
 29.95, 'USD', 'InStock', 4.7, 110000,
 'https://www.amazon.com/dp/B07QJWZK6H', 'Hydro Flask',
 '["TempShield insulation","Durable stainless steel","Lifetime-friendly refill bottle"]',
 'PUBLISHED', 'Hydro Flask Water Bottle Deal | DealStoker',
 'Stay hydrated outdoors with a trusted insulated bottle — Amazon.com pricing.',
 (SELECT id FROM categories WHERE slug = 'outdoor-sports'), NOW(), NOW()),

('AMAZON', 'B08TJ29J7W', 'www.amazon.com',
 'LEVOIT Air Purifier for Home Allergies and Pets',
 'levoit-core-300-air-purifier',
 'Compact HEPA air purifier designed for bedrooms and living rooms with quiet sleep mode.',
 'https://m.media-amazon.com/images/I/71Q5oZ8bQGL._AC_SL1500_.jpg',
 79.99, 'USD', 'InStock', 4.7, 180000,
 'https://www.amazon.com/dp/B08TJ29J7W', 'LEVOIT',
 '["H13 True HEPA filtration","Quiet sleep mode","Compact footprint"]',
 'PUBLISHED',
 NULL,
 NULL,
 (SELECT id FROM categories WHERE slug = 'home-kitchen'), NOW(), NOW()),

('AMAZON', 'B09VXN9W8Z', 'www.amazon.com',
 'Resistance Bands Set with Door Anchor and Handles',
 'resistance-bands-set-home-workout',
 'A portable strength-training kit for home workouts, travel, and warm-ups.',
 'https://m.media-amazon.com/images/I/71vZ4dQK8dL._AC_SL1500_.jpg',
 24.99, 'USD', 'InStock', 4.6, 45000,
 'https://www.amazon.com/dp/B09VXN9W8Z', 'Generic',
 '["Multiple resistance levels","Door anchor included","Carry bag for travel"]',
 'PUBLISHED', 'Best Resistance Bands Set for Home Workouts | DealStoker',
 'Affordable resistance bands for home fitness — see features and Amazon price.',
 (SELECT id FROM categories WHERE slug = 'outdoor-sports'), NOW(), NOW()),

('AMAZON', 'B0C3R8QK7M', 'www.amazon.com',
 'Coleman Sundome 4-Person Tent',
 'coleman-sundome-4-person-tent',
 'A classic weekend camping tent with straightforward setup and weather-ready coverage.',
 'https://m.media-amazon.com/images/I/81Z5p7bG5cL._AC_SL1500_.jpg',
 89.99, 'USD', 'InStock', 4.5, 35000,
 'https://www.amazon.com/dp/B0C3R8QK7M', 'Coleman',
 '["Fits up to 4 people","WeatherTec flooring","Easy setup poles"]',
 'PUBLISHED', 'Coleman Sundome 4-Person Tent Deal | DealStoker',
 'Weekend camping made easier — Coleman Sundome overview and Amazon.com link.',
 (SELECT id FROM categories WHERE slug = 'outdoor-sports'), NOW(), NOW());

INSERT INTO product_categories (product_id, category_id, is_primary)
SELECT p.id, p.primary_category_id, TRUE
FROM products p
WHERE p.primary_category_id IS NOT NULL;
